#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

#exec git update-server-info

PRE=$(git rev-parse 'HEAD@{1}')
POST=$(git rev-parse HEAD)
SYMNAME=$(git rev-parse --symbolic-full-name HEAD)
echo "$PRE $POST $SYMNAME" | git_buildbot.py
